import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Layout } from "antd";
import { Content, Footer, Header } from "antd/es/layout/layout";
import Sider from "antd/es/layout/Sider";
import NavMenu from "@/components/NavMenu";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "myNextApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Layout hasSider>
          <Sider
            collapsible
            collapsedWidth={52}
            width={160}
            style={{
              overflow: "auto",
              height: "100vh",
              position: "sticky",
              top: 0,
              bottom: 0,
            }}
          >
            <div className="logo" />
            <NavMenu />
          </Sider>
          <Layout>
            <Header className="header">ToDoList APP</Header>
            <Content className="content">{children}</Content>
            <Footer className="footer">© 2025 C.C.</Footer>
          </Layout>
        </Layout>
      </body>
    </html>
  );
}
